# project.yml
version: '3.8'

services:
  # Main TypeChat Application
  app:
    build: .
    container_name: typechat-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - typechat-net
    restart: unless-stopped

  # Database Service
  db:
    image: postgres:13-alpine
    container_name: typechat-db
    environment:
      - POSTGRES_USER=typechat
      - POSTGRES_PASSWORD=typechat123
      - POSTGRES_DB=typechat
    volumes:
      - typechat-data:/var/lib/postgresql/data
    networks:
      - typechat-net
    restart: unless-stopped

  # Redis for Caching/Real-time
  redis:
    image: redis:6-alpine
    container_name: typechat-redis
    ports:
      - "6379:6379"
    networks:
      - typechat-net
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    container_name: typechat-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - typechat-net
    restart: unless-stopped

  # Monitoring
  monitor:
    image: grafana/grafana
    container_name: typechat-monitor
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - typechat-net
    restart: unless-stopped

volumes:
  typechat-data:
  grafana-data:

networks:
  typechat-net:
    driver: bridge
